### ISSUE TITLE
Make immediate submit optional

### ISSUE THREAD

**Issue by johanneskoester** [Snakemake-Profiles/pbs-torque#1]
It would be desirable to make immediate submit an optional property of this profile (via cookiecutter). Many people will not want to use it like that.

**Comment by neilav** [comment]
Made this an option in cookiecutter and defaulted it be false. 

However, immediate submit just isn't going to work for this scheduler without the changes in my original pull request to hold all jobs until the end of submission and then release. Annoyingly, Torque does not allow dependencies to be set on jobs that have completed - even successful ones. Its a annoying quirk of this scheduler, alone.
