### ISSUE TITLE
Question: how to add default commands to every snakemake job?

### ISSUE THREAD

**Issue by fgvieira** [Snakemake-Profiles/pbs-torque#12]
Dear all,

I'm trying to use this profile with `snakemake`, but was wondering if it is possible to add extra commands to be run after the `snakemake` job. I've tried changing `pbs-jobscript.sh` to:
```
#!/bin/sh
# properties = {properties}
{exec_job}

hostname

qstat -f -1 $PBS_JOBID
```

but the last two commands are not executed.
How can I add some default commands to always be run with each `snakemake` job?

NOTE: I was not sure where to post it, so I've also posted it [here](https://github.com/snakemake/snakemake/issues/944#issue-851754097)

**Comment by brcopeland** [comment]
I was curious about this so I tried it myself and it works without issue for me.  I'd suggest making sure you're using the right profile and that your `config.yaml` file is specifying the proper jobscript (perhaps a copy you've made if you left the original alone).

**Comment by fgvieira** [comment]
Hi @brcopeland 

would you mind sending a copy of your profile?

The extra output (in this case `qstat`) will come on the cluster log, right? If not, where does it print this output?

thanks,

**Comment by brcopeland** [comment]
So I use the standard pbs-jobscript.sh that's in this repository but I just modified it to the following:
```
#!/bin/sh
# properties = {properties}
echo blah > /home/bcopeland/blah/xyz.out
{exec_job}
hostname

qstat -f -1 $PBS_JOBID
```

and when I ran a test Snakefile snakemake produced the following output:
```
Jobscript:
#!/bin/sh
# properties = {"type": "single", "rule": "blahrule", "local": false, "input": [], "output": ["blah.txt"], "wildcards": {}, "params": {}, "log": [], "threads": 1, "resources": {}, "jobid": 0, "cluster": {}}
echo blah > /home/bcopeland/blah/xyz.out
 cd /home/bcopeland/blah && \
PATH='/home/bcopeland/miniconda3/bin':$PATH /home/bcopeland/miniconda3/bin/python3.8 \
-m snakemake blahrule --snakefile /home/bcopeland/blah/Snakefile \
--force -j --keep-target-files --keep-remote --max-inventory-time 0 \
--wait-for-files /home/bcopeland/blah/.snakemake/tmp.b9dp58vo --latency-wait 5 \
 --attempt 1 --force-use-threads --scheduler ilp \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
   --allowed-rules blahrule --nocolor --notemp --no-hooks --nolock \
--mode 2  && exit 0 || exit 1
hostname

qstat -f -1 $PBS_JOBID
```

I confirmed that the created job script submitted to the cluster matched this and that its execution created the file I specified.

As far as the output from `hostname` and `qstat` that would go wherever `qsub` is saving your `stdout`.

**Comment by fgvieira** [comment]
But did you check if you got the output from `qstat -f -1 $PBS_JOBID`?
My script looks similar to yours, but I cannot find the output from the `qstat` command anywhere!

Could it be because of the `  && exit 0 || exit 1` at the end of the `snakemake` run? It looks like it terminates the script, so the `qstat` command is never executed...

**Comment by brcopeland** [comment]
Ah, sorry yes you're right.  The job will certainly exit there.  You could change `self.exec_job += " && exit 0 || exit 1"` at https://github.com/snakemake/snakemake/blob/81922b6200cbf5b62bf27737e12e0905ce8c540f/snakemake/executors/__init__.py#L914 to `self.exec_job += " || exit 1"`, which would cause it only exit after a failure or capture and process the return code later if you don't want it to exit in that case either.

**Comment by fgvieira** [comment]
Ok, but that would require changing `snakemake` code.
I'll open an issue there suggesting it.

Thanks!
