### ISSUE TITLE
has anyone tried using this with pbs-pro?

### ISSUE THREAD

**Issue by jhamman** [Snakemake-Profiles/pbs-torque#7]
I am wondering how applicable this profile would be for use on a PBS-Pro cluster. Has anyone tried this yet? Is there anything particular to torque in `pbs-submit.py`?

**Comment by neilav** [comment]
I haven't tried it myself I'm afraid. I guess there could be slight differences in syntax that might cause it to error. Is PBSPro free to download?

**Comment by jhamman** [comment]
@neilav - My understanding is yes: http://www.pbspro.org/Download.aspx#download

I think they are mostly compatible but my understanding is there are a few subtle differences.

Maybe you can help me with this more basic question. What does using the pbs-torque profile offer over the default snakemake options? What is the core functionality that motivated the development of this profile?

**Comment by neilav** [comment]
It doesn't particularly offer any functionality that you can't already do in snakemake via cluster configuration... it just helps to package a nice set of defaults. In my case I want all jobs in my pipelines to be submit using immediate submit and I want to set the job resources on a per rule basis.

**Comment by jhamman** [comment]
Cool. Thanks for the response. I think I get what's going on here now. I may give it another try and see how it works on PBS-pro. Will close this issue for now and report back if/when I have more information.
